version: '3'

services:
  metabase:
    image: metabase/metabase
    ports:
      - "3000:3000"
    # environment:
    #   - MB_DB_TYPE=mongodb
    #   - MB_DB_DBNAME=ponderada
    #   - MB_DB_PORT=27017
    #   - MB_DB_USER=albertomiranda
    #   - MB_DB_PASS=sA8R8Ht5RgfDv2ed
    #   - MB_DB_HOST=ponderada.gqg09ym.mongodb.net
